# Generated by Django 2.2.7 on 2020-07-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Combos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
